---
# Install Tools
- name: Install Security and IT Tools
  hosts: "{{ target_hosts | default('all') }}"
  become: true
  gather_facts: true

  vars:
    go_version: "1.23.2"
    python_version: "3.11.9"
    tools_dir: "/opt/tools"
    tmux_log_path: /root/logs/tmux
    tpm_path: /root/.tmux/plugins/tpm
    tmuxinator_config_path: /root/.config/tmuxinator
    selected_roles: [
      'environment_prep',
      'go_tools',
      'pipx_tools',
      'misc_tools',
      'metasploit',
      'seclists',
      'cleanup'
    ]

  pre_tasks:
    - name: Get root user's shell
      shell: "getent passwd root | cut -d: -f7"
      register: shell_output
      tags: always

    - name: Set root_user_shell variable
      tags: always
      set_fact:
        root_user_shell: "{{ shell_output.stdout }}"

    - name: Set shell_rc_file based on root user's shell
      tags: always
      set_fact:
        shell_rc_file: >-
          {% if root_user_shell.endswith('bash') %}
            /root/.bashrc
          {% elif root_user_shell.endswith('zsh') %}
            /root/.zshrc
          {% else %}
            /root/.bashrc
          {% endif %}

  roles:
    - role: environment_prep
      when: "'environment_prep' in selected_roles"
      tags: ['environment_prep']
    
    - role: go_tools
      when: "'go_tools' in selected_roles"
      tags: ['go_tools']
    
    - role: pipx_tools
      when: "'pipx_tools' in selected_roles"
      tags: ['pipx_tools']
    
    - role: misc_tools
      when: "'misc_tools' in selected_roles"
      tags: ['misc_tools']
    
    - role: metasploit
      when: "'metasploit' in selected_roles"
      tags: ['metasploit']
    
    - role: seclists
      when: "'seclists' in selected_roles"
      tags: ['seclists']
    
    - role: cleanup
      when: "'cleanup' in selected_roles"
      tags: ['cleanup']
