# site.yml - Main playbook
- name: Install Security and IT Tools
  hosts: "{{ target_hosts | default('all') }}"
  become: true
  vars:
    go_version: "1.23.2"
    python_version: "3.11.9"
    tools_dir: "/opt/tools"

  tasks:
    # Detect Root User's Shell
    - name: Get root user's shell
      shell: "getent passwd root | cut -d: -f7"
      register: shell_output

    - name: Set root_user_shell variable
      set_fact:
        root_user_shell: "{{ shell_output.stdout }}"

    - name: Set shell_rc_file based on root user's shell
      set_fact:
        shell_rc_file: >-
          {% if root_user_shell.endswith('bash') %}
            /root/.bashrc
          {% elif root_user_shell.endswith('zsh') %}
            /root/.zshrc
          {% else %}
            /root/.bashrc
          {% endif %}
    # System Preparation
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install system dependencies
      package:
        name:
          - git
          - curl
          - wget
          - build-essential
          - python3-pip
          - python3-venv
          - nmap
          - jq
          - make
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - llvm
          - libncursesw5-dev
          - xz-utils
          - tk-dev
          - libxml2-dev
          - libxmlsec1-dev
          - libffi-dev
          - liblzma-dev
          - libpcap-dev
        state: present

    - name: Install Chromium browser
      package:
        name: "{{ chromium_package_name }}"
        state: present
      vars:
        chromium_package_name: >-
          {{
            {
              'Ubuntu': 'chromium-browser',
              'Debian': 'chromium',
              'CentOS': 'chromium',
              'Fedora': 'chromium',
              'openSUSE Leap': 'chromium'
            }[ansible_distribution] | default('chromium')
          }}

    # Go Installation
    - name: Check existing Go installations
      stat:
        path: "{{ item }}"
      register: go_installations
      with_items:
        - "/usr/local/go"
        - "/usr/bin/go"
        - "/usr/local/bin/go"

    - name: Remove Go if installed via package manager
      package:
        name: golang
        state: absent
      when: ansible_os_family in ["Debian", "RedHat"]

    - name: Remove existing Go installation directories
      file:
        path: "{{ item.stat.path }}"
        state: absent
      when: item.stat.exists
      with_items: "{{ go_installations.results }}"

    - name: Download Go
      get_url:
        url: "https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz"
        dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
        mode: '0644'

    - name: Extract Go
      unarchive:
        src: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
        dest: /usr/local
        remote_src: yes

    - name: Check for existing go lines
      lineinfile:
        path: "{{ shell_rc_file | trim }}"
        line: "{{ item }}"
        state: absent
      check_mode: yes
      register: go_env_check
      with_items:
        - 'export PATH=$PATH:/usr/local/go/bin'
        - 'export GOPATH=/root/go'
        - 'export PATH=$PATH:$GOPATH/bin'
        
    - name: Set Go environment in profile
      blockinfile:
        path: /etc/profile
        marker: "# {mark} ANSIBLE MANAGED BLOCK - GO ENVIRONMENT"
        block: |
          export PATH=$PATH:/usr/local/go/bin
          export GOPATH=/root/go
          export PATH=$PATH:$GOPATH/bin
      when: go_env_check.results | map(attribute='found') | list | min == false

    # Create tools directory
    - name: Create tools directory
      file:
        path: "{{ tools_dir }}"
        state: directory
        mode: '0755'

    # Pyenv Installation and Setup
    - name: Download pyenv installer
      get_url:
        url: https://pyenv.run
        dest: /tmp/pyenv-installer
        mode: '0755'

    - name: Execute pyenv installer
      command: /tmp/pyenv-installer
      args:
        creates: /root/.pyenv


    - name: Check for existing pyenv lines
      lineinfile:
        path: "{{ shell_rc_file | trim }}"
        line: "{{ item }}"
        state: absent
      check_mode: yes
      register: pyenv_check
      with_items:
        - 'export PYENV_ROOT="/root/.pyenv"'
        - 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"'
        - 'eval "$(pyenv init -)"'
    - name: Configure pyenv in shell profile
      blockinfile:
        path: "{{ shell_rc_file | trim }}"
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK - PYENV CONFIGURATION"
        block: |
          export PYENV_ROOT="/root/.pyenv"
          command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init -)"
      when: pyenv_check.results | map(attribute='found') | list | min == false

    # Install Python with pyenv using full path
    - name: Install Python version with pyenv
      shell: |
        export PYENV_ROOT="/root/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(/root/.pyenv/bin/pyenv init -)"
        /root/.pyenv/bin/pyenv install {{ python_version }} -s
        /root/.pyenv/bin/pyenv global {{ python_version }}
      args:
        executable: "{{ root_user_shell }}"
        creates: "/root/.pyenv/versions/{{ python_version }}"

    # Install Go-based tools
    - name: Install Go-based tools
      environment:
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
        GOPATH: "/root/go"
      command: "go install -v {{ item }}@latest"
      args:
        creates: "/root/go/bin/{{ item | basename }}"
      with_items:
        - "github.com/projectdiscovery/nuclei/v3/cmd/nuclei"
        - "github.com/projectdiscovery/subfinder/v2/cmd/subfinder"
        - "github.com/projectdiscovery/httpx/cmd/httpx"
        - "github.com/projectdiscovery/naabu/v2/cmd/naabu"
        - "github.com/projectdiscovery/uncover/cmd/uncover"
        - "github.com/haccer/subjack"
        - "github.com/ffuf/ffuf/v2"
    - name: Clone TruffleHog repository
      git:
        repo: https://github.com/trufflesecurity/trufflehog.git
        dest: /opt/tools/trufflehog
        clone: yes
        update: yes
    
    - name: Install TruffleHog using Go
      environment:
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
        GOPATH: "/root/go"
      command: go install
      args:
        chdir: /opt/tools/trufflehog/
        creates: "/root/.go/bin/trufflehog"

    # Python Tools and Environments
    - name: Check if Hostess-Pie directory exists
      stat:
        path: "{{ tools_dir }}/Hostess-Pie"
      register: hostess_pie_dir

    - name: Clone Hostess-Pie repository
      git:
        repo: "https://github.com/burmat/Hostess-Pie.git"
        dest: "{{ tools_dir }}/Hostess-Pie"
      when: not hostess_pie_dir.stat.exists

    - name: Setup Hostess-Pie virtual environment
      pip:
        name: colorama
        virtualenv: "{{ tools_dir }}/Hostess-Pie"
        virtualenv_command: python3 -m venv
    - name: Check if /usr/share/seclists directory exists
      stat:
        path: "/usr/share/seclists"
      register: seclists_dir

    - name: Clone seclists repository
      git:
        repo: "https://github.com/danielmiessler/SecLists.git"
        dest: "/usr/share/seclists"
      when: not seclists_dir.stat.exists

    - name: Check if FGDS directory exists
      stat:
        path: "{{ tools_dir }}/Fast-Google-Dorks-Scan"
      register: fgds_dir

    - name: Clone FGDS repository
      git:
        repo: "https://github.com/IvanGlinkin/Fast-Google-Dorks-Scan.git"
        dest: "{{ tools_dir }}/Fast-Google-Dorks-Scan"
      when: not fgds_dir.stat.exists

    # Feroxbuster Installation
    - name: Determine if system is 32 or 64 bit Linux
      set_fact:
        is_linux32: "{{ ansible_facts['architecture'] == 'i686' }}"
        is_linux64: "{{ ansible_facts['architecture'] == 'x86_64' }}"

    - name: Set download URL for 32-bit Linux
      set_fact:
        feroxbuster_url: "https://github.com/epi052/feroxbuster/releases/latest/download/x86-linux-feroxbuster.zip"
      when: is_linux32

    - name: Set download URL for 64-bit Linux
      set_fact:
        feroxbuster_url: "https://github.com/epi052/feroxbuster/releases/latest/download/x86_64-linux-feroxbuster.zip"
      when: is_linux64

    - name: Download Feroxbuster binary
      get_url:
        url: "{{ feroxbuster_url }}"
        dest: "/tmp/feroxbuster.zip"
        mode: '0644'

    - name: Unzip Feroxbuster binary
      unarchive:
        src: "/tmp/feroxbuster.zip"
        dest: "/usr/local/bin"
        remote_src: yes
        mode: '0755'

    - name: Ensure Feroxbuster is executable
      file:
        path: "/usr/local/bin/feroxbuster"
        mode: '0755'
        state: file

    - name: Set aquatone download URL for 64-bit Linux
      set_fact:
        aquatone_url: "https://github.com/michenriksen/aquatone/releases/latest/download/aquatone_linux_amd64_1.7.0.zip"
      when: is_linux64

    - name: Download aquatone binary
      get_url:
        url: "{{ aquatone_url }}"
        dest: "/tmp/aquatone.zip"
        mode: '0644'

    - name: Unzip aquatone binary
      unarchive:
        src: "/tmp/aquatone.zip"
        dest: "/usr/local/bin"
        remote_src: yes
        mode: '0755'

    - name: Ensure aquatone is executable
      file:
        path: "/usr/local/bin/aquatone"
        mode: '0755'
        state: file

    # Pipx and Related Tools
    - name: Install pipx
      environment:
        PYENV_ROOT: "/root/.pyenv"
        PATH: "/root/.pyenv/bin:{{ ansible_env.PATH }}"
      pip:
        name: pipx
        state: latest
        executable: /root/.pyenv/versions/{{ python_version }}/bin/pip3

    - name: Check for existing pipx destinatinon path lines
      lineinfile:
        path: "{{ shell_rc_file | trim }}"
        line: "{{ item }}"
        state: absent
      check_mode: yes
      register: pipx_path_check
      with_items:
        - 'export PATH=$PATH:/root/.local/bin'

    - name: Add /root/.local/bin to PATH in shell profile
      when: pipx_path_check.results | map(attribute='found') | list | min == false
      blockinfile:
        path: "{{ shell_rc_file | trim }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - ADD /root/.local/bin TO PATH"
        block: |
          export PATH=$PATH:/root/.local/bin

    - name: Install pipx-based tools
      environment:
        PYENV_ROOT: "/root/.pyenv"
        PATH: "/root/.pyenv/bin:{{ ansible_env.PATH }}"
      command: "/root/.pyenv/shims/pipx install {{ item }}"
      args:
        creates: "/root/.local/bin/{{ item | basename }}"
      with_items:
        - "bbot"
        - "git+https://github.com/EnableSecurity/wafw00f.git"
        - "git+https://github.com/Pennyw0rth/NetExec"

    # Trevor Tools Installation
    - name: Install Trevor tools
      environment:
        PYENV_ROOT: "/root/.pyenv"
        PATH: "/root/.pyenv/bin:{{ ansible_env.PATH }}"
      pip:
        name:
          - "git+https://github.com/blacklanternsecurity/trevorproxy"
          - "git+https://github.com/blacklanternsecurity/trevorspray"
        executable: /root/.pyenv/versions/{{ python_version }}/bin/pip3

    # Final Verification
    - name: Verify tool installations
      stat:
        path: "{{ item }}"
      register: tool_checks
      with_items:
        - "/root/go/bin/nuclei"
        - "/root/go/bin/subfinder"
        - "/root/go/bin/httpx"
        - "/root/go/bin/naabu"
        - "/root/go/bin/uncover"
        - "/root/go/bin/subjack"
        - "/root/go/bin/ffuf"
        - "/usr/local/bin/feroxbuster"
        - "/root/.local/bin/bbot"
        - "/root/.local/bin/wafw00f"
        - "/root/.local/bin/nxc"
        - "/usr/local/bin/aquatone"
        - "/root/go/bin/trufflehog"
        - "/usr/share/seclists"
        - "/usr/local/bin/feroxbuster"
