# roles/cleanup/tasks/main.yml
---
# Check temporary files existence
- name: Check temporary files existence
  stat:
    path: "{{ item }}"
  register: temp_files
  with_items:
    - "/tmp/aquatone.zip"
    - "/tmp/feroxbuster.zip"
    - "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    - "/tmp/pyenv-installer"

# Cleanup temporary downloaded files
- name: Remove temporary downloaded files
  file:
    path: "{{ item.stat.path }}"
    state: absent
  when: item.stat.exists
  with_items: "{{ temp_files.results }}"

# Define build directories and corresponding binaries
- name: Define build directories and corresponding binaries
  set_fact:
    build_items:
      - dir: "{{ tools_dir }}/massdns"
        binary: "/usr/local/bin/massdns"
      - dir: "{{ tools_dir }}/trufflehog"
        binary: "/root/go/bin/trufflehog"

# Remove build directories if corresponding binaries exist
- name: Remove build directories if corresponding binaries exist
  stat:
    path: "{{ item.dir }}"
  register: dir_stat
  loop: "{{ build_items }}"
  loop_control:
    label: "{{ item.dir }}"
    loop_var: item

- name: Remove build directories if corresponding binaries exist
  stat:
    path: "{{ item.binary }}"
  register: binary_stat
  loop: "{{ build_items }}"
  loop_control:
    label: "{{ item.binary }}"
    loop_var: item

- name: Remove build directories if corresponding binaries exist
  file:
    path: "{{ item.item.dir }}"
    state: absent
  when:
    - item.stat.exists
    - binary_stat.results[item_index].stat.exists
  loop: "{{ dir_stat.results }}"
  loop_control:
    loop_var: item
    index_var: item_index

# Add cleanup success notification
- name: Notify about cleanup completion
  debug:
    msg: "Cleanup completed successfully. Removed existing temporary files and verified build directories."
  when:
    - temp_files.results | selectattr('stat.exists') | list | length > 0
    - dir_stat.results | selectattr('stat.exists') | list | length > 0