# roles/cleanup/tasks/main.yml
---
# Check temporary files existence
- name: Check temporary files existence
  stat:
    path: "{{ item }}"
  register: temp_files
  with_items:
    - "/tmp/aquatone.zip"
    - "/tmp/feroxbuster.zip"
    - "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    - "/tmp/pyenv-installer"

# Cleanup temporary downloaded files
- name: Remove temporary downloaded files
  file:
    path: "{{ item.stat.path }}"
    state: absent
  when: item.stat.exists
  with_items: "{{ temp_files.results }}"

- name: Define build directories and corresponding binaries
  set_fact:
    build_items:
      - dir: "{{ tools_dir }}/massdns"
        binary: "/usr/local/bin/massdns"
      - dir: "{{ tools_dir }}/trufflehog"
        binary: "/root/go/bin/trufflehog"

- name: Remove build directories if corresponding binaries exist
  file:
    path: "{{ item.dir }}"
    state: absent
  when:
    - lookup('ansible.builtin.stat', item.dir, get_attributes=False).stat.exists
    - lookup('ansible.builtin.stat', item.binary, get_attributes=False).stat.exists
  loop: "{{ build_items }}"
  loop_control:
    loop_var: item

- name: Notify about cleanup completion
  debug:
    msg: "Cleanup completed successfully. Removed existing temporary files and verified build directories."
  when:
    - temp_files.results | selectattr('stat.exists') | list | length > 0
    - build_items | selectattr('dir', 'in', removed_dirs) | list | length > 0
  vars:
    removed_dirs: "{{ build_items | map(attribute='dir') | list }}"