# roles/miscellaneous/tasks/main.yml
---
- name: Create tools directory
  file:
    path: "{{ tools_dir }}"
    state: directory
    mode: '0755'

# Feroxbuster Installation
- name: Determine if system is 32 or 64 bit Linux
  set_fact:
    is_linux32: "{{ ansible_facts['architecture'] == 'i686' }}"
    is_linux64: "{{ ansible_facts['architecture'] == 'x86_64' }}"

- name: Set download URL for 32-bit Linux
  set_fact:
    feroxbuster_url: "https://github.com/epi052/feroxbuster/releases/latest/download/x86-linux-feroxbuster.zip"
  when: is_linux32

- name: Set download URL for 64-bit Linux
  set_fact:
    feroxbuster_url: "https://github.com/epi052/feroxbuster/releases/latest/download/x86_64-linux-feroxbuster.zip"
  when: is_linux64

- name: Download Feroxbuster binary
  get_url:
    url: "{{ feroxbuster_url }}"
    dest: "/tmp/feroxbuster.zip"
    mode: '0644'

- name: Unzip Feroxbuster binary
  unarchive:
    src: "/tmp/feroxbuster.zip"
    dest: "/usr/local/bin"
    remote_src: yes
    mode: '0755'

- name: Ensure Feroxbuster is executable
  file:
    path: "/usr/local/bin/feroxbuster"
    mode: '0755'
    state: file

# MassDNS
- name: Check if massdns directory exists
  stat:
    path: "{{ tools_dir }}/massdns"
  register: massdns_dir

- name: Check if massdns binary exists
  stat:
    path: "/usr/local/bin/massdns"
  register: massdns_bin

- name: Clone MassDNS repository
  git:
    repo: "https://github.com/blechschmidt/massdns.git"
    dest: "{{ tools_dir }}/massdns"
    version: master
  when: not massdns_dir.stat.exists

- name: Build MassDNS
  make:
    chdir: "{{ tools_dir }}/massdns"
    target: all
  when: not massdns_bin.stat.exists

- name: Copy MassDNS binary to /usr/local/bin
  copy:
    src: "{{ tools_dir }}/massdns/bin/massdns"
    dest: /usr/local/bin/massdns
    mode: '0755'
    remote_src: yes
  when: not massdns_bin.stat.exists

# Hostess-Pie
- name: Check if Hostess-Pie directory exists
  stat:
    path: "{{ tools_dir }}/Hostess-Pie"
  register: hostess_pie_dir

- name: Clone Hostess-Pie repository
  git:
    repo: "https://github.com/burmat/Hostess-Pie.git"
    dest: "{{ tools_dir }}/Hostess-Pie"
  when: not hostess_pie_dir.stat.exists

- name: Setup Hostess-Pie virtual environment
  pip:
    name: colorama
    virtualenv: "{{ tools_dir }}/Hostess-Pie"
    virtualenv_command: python3 -m venv

# SQLMap
- name: Check if sqlmap directory exists
  stat:
    path: "{{ tools_dir }}/sqlmap"
  register: sqlmap_dir

- name: Clone sqlmap repository
  git:
    repo: "https://github.com/sqlmapproject/sqlmap.git"
    dest: "{{ tools_dir }}/sqlmap"
    version: master
  when: not sqlmap_dir.stat.exists

# FGDS (Fast Google Dorks Scan)
- name: Check if FGDS directory exists
  stat:
    path: "{{ tools_dir }}/Fast-Google-Dorks-Scan"
  register: fgds_dir

- name: Clone FGDS repository
  git:
    repo: "https://github.com/IvanGlinkin/Fast-Google-Dorks-Scan.git"
    dest: "{{ tools_dir }}/Fast-Google-Dorks-Scan"
  when: not fgds_dir.stat.exists

# Trevor Tools Installation
- name: Install Trevor tools
  environment:
    PYENV_ROOT: "/root/.pyenv"
    PATH: "/root/.pyenv/bin:{{ ansible_env.PATH }}"
  pip:
    name:
      - "git+https://github.com/blacklanternsecurity/trevorproxy"
      - "git+https://github.com/blacklanternsecurity/trevorspray"
    executable: /root/.pyenv/versions/{{ python_version }}/bin/pip3